# Generated by Django 6.0 on 2025-12-22 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsessions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examsessions',
            name='standard_error',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='examsessions',
            name='total_information',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='examsessions',
            name='status',
            field=models.CharField(default='Ongoing', max_length=50),
        ),
    ]
