# Generated by Django 6.0 on 2025-12-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0002_examsessions_created_at_examsessions_standard_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsessions',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
