# Generated by Django 6.0 on 2025-12-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0003_examsessions_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsessions',
            name='selected_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='examsessions',
            name='session_type',
            field=models.CharField(choices=[('ADAPTIVE', 'Adaptive Exam'), ('PRACTICE', 'Practice Mode')], default='ADAPTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='examsessions',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
