# Generated by Django 6.0 on 2025-12-21 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_sessions', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField(default=list)),
                ('is_correct', models.BooleanField()),
                ('time_taken', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_sessions.examsessions')),
            ],
            options={
                'db_table': 'user_responses',
            },
        ),
    ]
