# Generated by Django 6.0 on 2025-12-21 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('options', models.JSONField(default=list)),
                ('correct_option_ids', models.JSONField(default=list)),
                ('rationale', models.TextField(blank=True)),
                ('difficulty_logit', models.FloatField()),
                ('category_ids', models.ManyToManyField(blank=True, to='categories.categories')),
                ('parent_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenarios')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
