# Generated by Django 6.0 on 2025-12-22 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='category_ids',
        ),
        migrations.AlterField(
            model_name='questions',
            name='difficulty_logit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='parent_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scenarios.scenarios'),
        ),
    ]
