# Generated by Django 6.0 on 2025-12-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('questions', '0002_remove_questions_category_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='category_ids',
            field=models.ManyToManyField(blank=True, related_name='questions', to='categories.categories'),
        ),
    ]
