# Generated by Django 6.0 on 2025-12-26 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questions_category_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Internal code used in system (e.g., 'SATA', 'MCQ')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="User-friendly name displayed in admin (e.g., 'Select All That Apply')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this question type and when to use it')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to hide from question creation without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Type',
                'verbose_name_plural': 'Question Types',
                'db_table': 'question_types',
                'ordering': ['display_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use question_type field instead', max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.ForeignKey(blank=True, help_text='Select the question type from the dropdown or add a new type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions.questiontype'),
        ),
    ]
