# Generated by Django 6.0 on 2025-12-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questiontype_alter_questions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='clinical_judgment_function',
            field=models.CharField(blank=True, choices=[('RECOGNIZE_CUES', 'Recognize Cues'), ('ANALYZE_CUES', 'Analyze Cues'), ('PRIORITIZE_HYPOTHESES', 'Prioritize Hypotheses'), ('GENERATE_SOLUTIONS', 'Generate Solutions'), ('TAKE_ACTIONS', 'Take Actions'), ('EVALUATE_OUTCOMES', 'Evaluate Outcomes')], help_text='NCJMM Clinical Judgment Function this question tests (for scenario questions)', max_length=50),
        ),
        migrations.AddField(
            model_name='questions',
            name='exhibit_updates',
            field=models.JSONField(blank=True, default=dict, help_text="New or updated exhibit tabs to show with this question. Format: {'Tab_Name': 'content', 'Labs_1200': 'New lab results...'}"),
        ),
        migrations.AddField(
            model_name='questions',
            name='scenario_question_number',
            field=models.IntegerField(blank=True, help_text='Question number within scenario (1-6 for NCLEX NGN). Questions will be delivered in this order.', null=True),
        ),
    ]
