# Generated by Django 6.0 on 2026-01-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_questions_clinical_judgment_function_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='hotspot_data',
            field=models.JSONField(blank=True, default=dict, help_text='Target coordinates. Click the image above to set this automatically.', null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='hotspot_image',
            field=models.ImageField(blank=True, help_text='Upload the image for the Hot Spot question here.', null=True, upload_to='hotspot_images/'),
        ),
    ]
