# Generated by Django 6.0 on 2026-01-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_questions_hotspot_data_questions_hotspot_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='hotspot_data',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='hotspot_image',
        ),
    ]
