# Generated by Django 6.0 on 2025-12-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_alter_scenarios_exhibits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='exhibits',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
