# Generated by Django 6.0 on 2025-12-31 07:31

import scenarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_alter_scenarios_exhibits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='exhibits',
            field=models.JSONField(blank=True, default=scenarios.models.get_default_exhibits),
        ),
    ]
