# Generated by Django 6.0 on 2025-12-24 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(help_text='Target NCLEX exam date')),
                ('daily_study_hours', models.IntegerField(default=2, help_text='Daily study goal in hours')),
                ('study_streak', models.IntegerField(default=0, help_text='Consecutive days with completed tasks')),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_plans',
            },
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('PRACTICE', 'Practice Questions'), ('REVIEW', 'Review Content'), ('MOCK_EXAM', 'Mock Exam'), ('CUSTOM', 'Custom Task')], default='CUSTOM', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('estimated_minutes', models.IntegerField(default=30, help_text='Estimated time in minutes')),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_minutes', models.IntegerField(blank=True, help_text='Actual time spent in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categories')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='study_planner.studyplan')),
            ],
            options={
                'db_table': 'study_tasks',
                'ordering': ['scheduled_date', '-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('total_minutes', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='study_planner.studyplan')),
            ],
            options={
                'db_table': 'study_sessions',
                'ordering': ['-session_date'],
                'unique_together': {('study_plan', 'session_date')},
            },
        ),
    ]
