# Generated by Django 6.0 on 2025-12-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studytask',
            name='completed',
        ),
        migrations.AddField(
            model_name='studytask',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='TODO', max_length=20),
        ),
    ]
