# Generated by Django 6.0 on 2025-12-24 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('questions_answered', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_daily_activity',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='gamificatio_user_id_d49560_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_code', models.CharField(db_index=True, max_length=50)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_badge',
                'ordering': ['-earned_date'],
                'indexes': [models.Index(fields=['user', 'badge_code'], name='gamificatio_user_id_82f045_idx'), models.Index(fields=['-earned_date'], name='gamificatio_earned__53de28_idx')],
                'unique_together': {('user', 'badge_code')},
            },
        ),
        migrations.CreateModel(
            name='UserGameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(db_index=True, default=0)),
                ('level', models.IntegerField(default=1)),
                ('current_streak', models.IntegerField(db_index=True, default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_profile',
                'indexes': [models.Index(fields=['-total_points'], name='gamificatio_total_p_5acc71_idx'), models.Index(fields=['-current_streak'], name='gamificatio_current_f2cff8_idx')],
            },
        ),
    ]
